
IF EXISTS (SELECT name FROM sys.indexes WHERE name = 'IX_Person_Slug')
BEGIN
	DROP INDEX [IX_Person_Slug] ON [dbo].[Person];
END
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_Person_Slug] ON [dbo].[Person]
(
	[PersonId] ASC,
	[Slug] ASC
)
INCLUDE (
 	[Name],
	[Email],
	[Location]
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
